services:
  autocomplete-service:
    build: ./autocomplete-service
    image: autocomplete-image:latest
    networks:
      - p2v-network
    environment:
      - IS_MINI

  search-service:
    build: ./search-service
    image: search-image:latest
    networks:
      - p2v-network
    environment:
      - IS_MINI

  web-server:
    build: ./web-server
    image: web-server-image:latest
    ports:
      - "3000:3000"
    networks:
      - p2v-network

networks:
  p2v-network:
    driver: bridge