services:
  autocomplete-service:
    build: ./autocomplete-service
    image: piyp791/autocomplete-image:latest
    networks:
      - p2v-network
    env_file:
      - .env
    deploy:
      replicas: 1

  search-service:
    build: ./search-service
    image: piyp791/search-image:latest
    networks:
      - p2v-network
    env_file:
      - .env
    deploy:
      replicas: 1

  web-server:
    build: ./web-server
    image: piyp791/web-server-image:latest
    ports:
      - "3000:3000"
    networks:
      - p2v-network
    deploy:
      replicas: 1

networks:
  p2v-network:
    driver: overlay